name: linting, testing, building, deploying
on:
    push:
        branches: [main]

jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x] # Лучше использовать LTS

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            # - name: Install dependencies
            #   run: npm ci

            # - name: Build production project
            #   run: npm run build:prod

            # - name: Lint TypeScript
            #   run: npm run lint:ts

            # - name: Lint SCSS
            #   run: npm run lint:scss

            # - name: Unit testing
            #   run: npm run test:unit

            # - name: Build Storybook
            #   run: npm run storybook:build

            # - name: Screenshot testing
            #   run: npm run test:ui:ci

            # 7️⃣ Debug step: проверить SSH ключ

            - name: Add SSH private key to agent
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Deploy to Server
              env:
                  SERVER_USER: ${{ secrets.SERVER_USER }}
                  SERVER_IP: ${{ secrets.SERVER_IP }}
                  APP_DIR: ${{ secrets.APP_DIR }}
              run: |
                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP << 'EOF'
                  set -e

                  mkdir -p $APP_DIR
                  cd $APP_DIR

                  git pull origin main

                  if [ ! -d ".git" ]; then
                    echo "📥 Клонируем репозиторий (первый деплой)..."
                    git clone git@github.com:Myrhoiazov/admin-panel.git .
                  else
                    echo "🔄 Обновляем репозиторий..."
                    git remote set-url origin git@github.com:Myrhoiazov/admin-panel.git
                    git pull origin main
                  fi

                  echo "🔧 Load NVM and Node environment..."
                  export NVM_DIR="/root/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  export PATH="$NVM_DIR/versions/node/v20.19.5/bin:$PATH"

                  echo "📦 Устанавливаем зависимости..."
                  npm install

                  echo "🏗️ Собираем проект..."
                  npm run build:prod

                  if [ -d "build" ]; then
                    echo "✅ Сборка завершена, build/ успешно создан!"
                  else
                    echo "❌ Ошибка: папка build не найдена."
                    exit 1
                  fi
                  EOF
