name: linting, testing, building, deploying
on:
    push:
        branches:
            - main # при пуше в main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            # - name: Install dependencies
            #   run: npm ci

            # - name: Build production project
            #   run: npm run build:prod

            # - name: Lint TypeScript
            #   run: npm run lint:ts

            # - name: Lint SCSS
            #   run: npm run lint:scss

            # - name: Unit testing
            #   run: npm run test:unit

            # - name: Build Storybook
            #   run: npm run storybook:build

            # - name: Screenshot testing
            #   run: npm run test:ui:ci

            # 7️⃣ Debug step: проверить SSH ключ
            - name: Connect to server and deploy
              uses: appleboy/ssh-action@v1.1.0
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      set -e

                      echo "🔧 Load NVM and Node environment..."
                      export NVM_DIR="/root/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                      export PATH="$NVM_DIR/versions/node/v20.19.5/bin:$PATH"

                      echo "✅ Pulling latest code..."
                      cd /var/www/project
                      
                      if [ ! -d "frontend/.git" ]; then
                        echo "📦 Cloning repository..."
                        git clone git@github.com:Myrhoiazov/admin-panel.git frontend
                      fi

                      cd frontend
                      git config --global --add safe.directory /var/www/project/frontend
                      git fetch --all
                      git pull origin main

                      echo "📦 Installing dependencies..."
                      npm install

                      echo "🧹 Cleaning old build artifacts..."
                      rm -rf build/

                      echo "⚙️ Building project..."
                      npm run build:prod || echo "no build step"

                      echo "♻️ Restarting PM2..."
                      pm2 restart frontend

                      echo "✅ Deployment complete :- ) !"
